apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: {{ .Values.movie.dbName }}
        volumeMounts:
        - name: {{ .Values.namespace }}-movie-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: {{ .Values.namespace }}-movie-db-data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-movie-db-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080