apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movieImage }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.movie.db }}
        - name: CAST_SERVICE_HOST_UR
          value: {{ .Values.movie.url }}
        volumeMounts:
        - name: {{ .Values.namespace }}-movie-service-data
          mounthPath: /app
      volumes:
      - name: {{ .Values.namespace }}-movie-service-data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-movie-service-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000