apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movie.service.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.movie.service.env.DATABASE_URI.value }}
        - name: CAST_SERVICE_HOST_URL
          value: {{ .Values.movie.service.env.CAST_SERVICE_HOST_URL.value }}
        volumeMounts:
        - name: movieservicedata-pv
          mountPath: ./app/
      volumes:
      - name: movieservicedata-pv
        persistentVolumeClaim:
          claimName: movieservicedata-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-movie-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movieservicedata-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/movie/prod/service/"
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movieservicedata-pvc
  namespace: {{ .Values.namespace }}
spec:
  volumeName: movieservicedata-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi