apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movie.service.image }}
      imagePullSecrets:
      - name: credentials-docker
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.movie.service.env.DATABASE_URI.value }}
        - name: CAST_SERVICE_HOST_URL
          value: {{ .Values.cast.service.env.CAST_SERVICE_HOST_URL.value }}
        volumeMounts:
        - name: {{ .Values.namespace }}-movie-service-data
          mountPath: /app
      volumes:
      - name: {{ .Values.namespace }}-movie-service-data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-movie-service-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000