apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: "cast_db_username"
        - name: POSTGRES_PASSWORD
          value: "cast_db_password"
        - name: POSTGRES_DB
          value: "cast_db_{{ .Values.namespace }}"
        volumeMounts:
        - name: cast-db-data-{{ .Values.namespace }}
          mounthPath: /var/lib/postgresql/data
      volumes:
      - name: cast-dbdata-{{ .Values.namespace }}
        persistentVolumeClaim:
          claimName: cast-db-claim-{{ .Values.namespace }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080