apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: julienvb/labo:movie-service-1.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
        - name: CAST_SERVICE_HOST_UR
          value: "http://cast_service:8000/api/v1/casts/"
        volumeMounts:
        - name: movie-service-data-dev
          mounthPath: /app
      volumes:
      - name: movie-service-data-dev
        persistentVolumeClaim:
          claimName: movie-service-claim-dev
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service-service
  namespace: dev
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000