namespace: prod

movie:
  service:
    ingress:
      url: prod-movie.vambalthoven.cloudns.biz
    env:
      DATABASE_URI:
        value: postgresql://movie_db_username:movie_db_password@prod-movie-db-service:80/movie_db_prod
      CAST_SERVICE_HOST_URL:
        value: prod-cast-service-service
  db:
    env:
      POSTGRES_DB:
        value: movie_db_prod
    data:
      volumeMounts:
        name: prod-moviedbdata-pv
      persistentVolumeClaim:
        name: prod-moviedbdata-pvc
      hostPath:
        path: "/datascientest-jenkins/prod/movie/db/"
cast:
  service:
    ingress:
      url: prod-cast.vambalthoven.cloudns.biz
    env:
      DATABASE_URI:
        value: postgresql://cast_db_username:cast_db_password@prod-cast-db-service:80/cast_db_prod
  db:
    env:
      POSTGRES_DB:
        value: cast_db_prod
    data:
      volumeMounts:
        name: prod-castdbdata-pv
      persistentVolumeClaim:
        name: prod-castdbdata-pvc
      hostPath:
        path: "/datascientest-jenkins/prod/cast/db/"