apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db-statefulset
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db
        image: {{ .Values.cast.db.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.cast.db.env.POSTGRES_USER.value }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.cast.db.env.POSTGRES_PASSWORD.value }}
        - name: POSTGRES_DB
          value: {{ .Values.cast.db.env.POSTGRES_DB.value }}
        volumeMounts:
        - name: {{ .Values.cast.db.data.volumeMounts.name }}
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: {{ .Values.cast.db.data.volumeMounts.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.cast.db.data.persistentVolumeClaim.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-cast-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.cast.db.data.volumeMounts.name }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.cast.db.data.hostPath.path }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cast.db.data.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  volumeName: {{ .Values.cast.db.data.volumeMounts.name }}
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi