apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.cast.image }}
      imagePullSecrets:
      - name: credentials-docker
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.cast.db }}
        volumeMounts:
        - name: {{ .Values.namespace }}-cast-service-data
          mountPath: /app
      volumes:
      - name: {{ .Values.namespace }}-cast-service-data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-cast-service-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000