apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.cast.service.image }}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: {{ .Values.cast.service.env.DATABASE_URI.value }}
        volumeMounts:
        - name: castservicedata-pv
          mountPath: ./app/
      volumes:
      - name: castservicedata-pv
        persistentVolumeClaim:
          claimName: castservicedata-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-cast-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: castservicedata-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cast/prod/service/"
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castservicedata-pvc
  namespace: {{ .Values.namespace }}
spec:
  volumeName: castservicedata-pv
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi