apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: {{ .Values.cast.db.env.POSTGRES_USER.value }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.cast.db.env.POSTGRES_PASSWORD.value }}
        - name: POSTGRES_DB
          value: {{ .Values.cast.db.env.POSTGRES_DB.value }}
        volumeMounts:
        - name: {{ .Values.namespace }}-cast-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: {{ .Values.namespace }}-cast-db-data
        persistentVolumeClaim:
          claimName: {{ .Values.namespace }}-cast-db-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080