movie:
  service:
    image: julienvb/datascientest:movie-service
  db:
    image: postgres:12.1-alpine
    env:
      POSTGRES_USER:
        value: movie_db_username
      POSTGRES_PASSWORD:
        value: movie_db_password
cast:
  service:
    image: julienvb/datascientest:cast-service
  db:
    image: postgres:12.1-alpine
    env:
      POSTGRES_USER:
        value: cast_db_username
      POSTGRES_PASSWORD:
        value: cast_db_password